services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"  #standard web interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access Docker Engine
      - ./portainer:/data
    restart: unless-stopped
